# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread
from PyQt5.QtWidgets import QWidget, QGridLayout, QPushButton, QApplication
from POSvariable import TABLE_NUM
from table_info import tableInfoWidget
from POSsql import Tablectrl
import threading


tablectrl = Tablectrl()
 
class tableWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi()
    
    def setupUi(self):
        self.setObjectName("Form")
        self.resize(717, 678)
        self.setMinimumSize(QtCore.QSize(717, 678))
        self.setMaximumSize(QtCore.QSize(717, 678))
        self.tableInfoWidget = QWidget(self)
        self.tableInfoWidget.setGeometry(QtCore.QRect(0, 0, 711, 671))
        self.tableInfoWidget.setMinimumSize(QtCore.QSize(711, 671))
        self.tableInfoWidget.setMaximumSize(QtCore.QSize(711, 671))
        self.tableInfoWidget.setObjectName("tableInfoWidget")
        self.gridLayoutWidget = QWidget(self.tableInfoWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, -28, 701, 732))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.retranslateUi(TABLE_NUM)
        #self.totalinfo(TABLE_NUM)
        
        #i=1
        #for x in range(0,5):
        #    for y in range(0,5):
        #        self.btnlist = QtWidgets.QPushButton(self)
        #        self.btnlist.setMinimumSize(QtCore.QSize(0, 110))
        #        self.btnlist.setObjectName('pushButton_{}'.format(i))
        #        self.gridLayout.addWidget(self.btnlist, x, y, 1, 1)
        #        i+=1
        for z in range(1,TABLE_NUM+1):
            child = self.findChild(QPushButton, 'pushButton_{}'.format(z))
            child.clicked.connect(self.tableinfo)
        
        
        #QtCore.QMetaObject.connectSlotsByName()

    def retranslateUi(self,count):
        #self.tableInfoWidget.clear()
        #self.show()
        i=1
        for x in range(0,5):
            for z in range(0,5):
                self.btnlist = QtWidgets.QPushButton(self)
                self.btnlist.setMinimumSize(QtCore.QSize(0, 110))
                self.btnlist.setObjectName('pushButton_{}'.format(i))
                self.gridLayout.addWidget(self.btnlist, x, z, 1, 1)
                i+=1
    #def totalinfo(self,count):
        for y in range(1,count+1):
            total = tablectrl.orderTotal(y)
            #print(total)
            child = self.findChild(QPushButton, 'pushButton_{}'.format(y))
            #print(child)
            if y >= 10:
                table_counger = '{0}번 테이블 \n\n\n {1}원'.format(y,total)
            else:
                table_counger = '0{0} 번 테이블 \n\n\n {1}원'.format(y,total)
            #child.clear()
            child.setText(table_counger)
            print(child.text())
            child.update()
            child.repaint()
            #child.refresh()
            QApplication.processEvents()
            
        #threading.Timer(2.5, self.retranslateUi()).start()   
            
    
    def tableinfo(self):
        table_num=int(self.sender().text()[0:2])
        self.tableInfo = tableInfoWidget()
        self.tableInfo.labeltext(table_num)
        self.tableInfo.menuLoading()
        self.tableInfo.billLoading()
        self.tableInfo.show()
        print('정보')
    
    #def show(self):
    #   self.close()
        
    
        
        
        
        


#if __name__ == "__main__":
#    app = QApplication(sys.argv)
#    ui = tableWidget()
#    ui.show()
#    sys.exit(app.exec_())
