# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from POSvariable import TABLE_NUM 
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QObject, QEvent
from PyQt5.QtWidgets import QWidget,QLabel,QApplication
from POSsql import Tablectrl
from table_info import tableInfoWidget
import POSvariable

tablectrl = Tablectrl

def clickable(widget):

        class Filter(QObject):
        
            clicked = pyqtSignal()	#pyside2 사용자는 pyqtSignal() -> Signal()로 변경
            def eventFilter(self, obj, event):
            
                if obj == widget:
                    if event.type() == QEvent.MouseButtonRelease:
                        if obj.rect().contains(event.pos()):
                            self.clicked.emit()
                            # The developer can opt for .emit(obj) to get the object within the slot.
                            return True
                return False
        filter = Filter(widget)
        widget.installEventFilter(filter)
        return filter.clicked

class table2Widgetm(QWidget):
        def __init__(self, parent=None):
                super().__init__(parent)
                self.setupUi()

        def setupUi(self):
                self.setObjectName("Form")
                self.resize(717, 677)
                self.setMinimumSize(QtCore.QSize(717, 677))
                self.setMaximumSize(QtCore.QSize(717, 677))
                self.tableInfoWidget = QtWidgets.QWidget(self)
                self.tableInfoWidget.setGeometry(QtCore.QRect(0, 0, 711, 671))
                self.tableInfoWidget.setMinimumSize(QtCore.QSize(711, 671))
                self.tableInfoWidget.setMaximumSize(QtCore.QSize(711, 671))
                self.tableInfoWidget.setObjectName("tableInfoWidget")
                self.gridLayoutWidget = QtWidgets.QWidget(self.tableInfoWidget)
                self.gridLayoutWidget.setGeometry(QtCore.QRect(0, -30, 701, 732))
                self.gridLayoutWidget.setObjectName("gridLayoutWidget")
                self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
                self.gridLayout.setContentsMargins(0, 0, 0, 0)
                self.gridLayout.setHorizontalSpacing(3)
                self.gridLayout.setVerticalSpacing(0)
                self.gridLayout.setObjectName("gridLayout")
                self.retranslateUi(TABLE_NUM)
                
                for z in range(1,TABLE_NUM+1):
                        child = self.findChild(QLabel, 'label_{}'.format(z))
                        clickable(child).connect(self.tableinfo)

                

                

                #QtCore.QMetaObject.connectSlotsByName(Form)
#
        def retranslateUi(self,count):
                i=1
                for x in range(0,5):
                        for z in range(0,5):
                                self.label = QtWidgets.QLabel(self.gridLayoutWidget)
                                self.label.setMinimumSize(QtCore.QSize(137, 100))
                                self.label.setMaximumSize(QtCore.QSize(137, 100))
                                self.label.setSizeIncrement(QtCore.QSize(0, 0))
                                self.label.setStyleSheet("QLabel {\n""    background-color: rgb(225, 225, 225);\n""    \n""}")
                                self.label.setAlignment(QtCore.Qt.AlignCenter)
                                self.label.setWordWrap(True)
                                self.label.setObjectName("label_{}".format(i))
                                self.gridLayout.addWidget(self.label, x, z, 1, 1)
                                i+=1
                for y in range(1,count+1):
                        total = tablectrl.orderTotal(self,y)
                        #print(total)
                        child = self.findChild(QLabel, 'label_{}'.format(y))
                        #print(child)
                        if y >= 10:
                            table_counger = '{0}번 테이블 \n\n\n {1}원'.format(y,total)
                        else:
                            table_counger = '0{0} 번 테이블 \n\n\n {1}원'.format(y,total)
                        #child.clear()
                        child.setText(table_counger)
                        #print(child.text())
                        child.update()
                        child.repaint()
                        QApplication.processEvents()


        def tableinfo(self):
                print(self.sender())
                print(self.findChild(QLabel, 'label_{}'.format(5)))
                for x in range(1,TABLE_NUM+1):
                        if self.sender() == self.findChild(QLabel, 'label_{}'.format(x)):
                                self.child = self.findChild(QLabel, 'label_{}'.format(x))
                                table_num=int(self.child.text()[0:2])
                                self.tableInfo = tableInfoWidget()
                                self.tableInfo.labeltext(table_num)
                                self.tableInfo.menuLoading()
                                self.tableInfo.billLoading()
                                self.tableInfo.show()
                                print('정보')
                                return x
                return 0
                
                
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = table2Widgetm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
